version: '3.8'
services:
  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodb
    ports:
      - 27018:27017
    volumes: # optional to preserve database after container is deleted.
      - ./database-data:/data/db